language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
         - php: 5.5
         - php: hhvm

before_script:
    - composer self-update
    - composer install --dev

script:
    - vendor/bin/phpunit
